spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 106522861457-4fvg3mj0frro335khb1c7ekkckdm75cb.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
      hibernate:
        type:
          descriptor:
            sql: TRACE

jwt:
  key: roseKnife23022088123647712893741234123412341234
  access-token-expiration-minutes: 10
  refresh-token-expiration-minutes: 300